services:
  postgres:
    image: postgres:16-alpine
    container_name: novatask-postgres
    environment:
      POSTGRES_DB: novatask
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build:
      context: ./backend
    container_name: novatask-backend
    depends_on:
      - postgres
    environment:
      PORT: 4000
      NODE_ENV: production
      CLIENT_URL: http://localhost:8080
      CLIENT_URLS: http://localhost:8080
      DATABASE_URL: postgresql://postgres:postgres@postgres:5432/novatask
      JWT_ACCESS_SECRET: change_this_access_secret
      JWT_REFRESH_SECRET: change_this_refresh_secret
      JWT_ACCESS_EXPIRES_IN: 15m
      JWT_REFRESH_EXPIRES_IN: 7d
      MAIL_ENABLED: "false"
    ports:
      - "4000:4000"

  frontend:
    build:
      context: ./frontend
    container_name: novatask-frontend
    depends_on:
      - backend
    ports:
      - "8080:80"

volumes:
  postgres_data:
